export const SET_USER_INFO = "SET_USER_INFO"
export const GET_CURRENCY = 'GET_CURRENCY'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const RESET_REDUCERS = 'RESET_REDUCERS'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const GET_CURRENT_CATEGORY = 'GET_CURRENT_CATEGORY'
export const UPDATE_INFO = 'UPDATE_INFO'
export const RESET_CATEGORIES = 'RESET_CATEGORIES'
export const GET_RECORDS = 'GET_RECORDS'
export const GET_CURRENT_RECORD = 'GET_CURRENT_RECORD'



